###testing server status
GET http://localhost:8000/

###get all the task from the database
GET http://localhost:8000/api/v1/task


###send task to the database
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
"task":"playing games",
"hr":"5",
"type":"entry"
}
###send task to the database
PATCH  http://localhost:8000/api/v1/task
 Content-Type: application/json

 {
"type":"bad",
"_id":"64850f070dd4b973eaf656df"
 }

###send task to the database
DELETE  http://localhost:8000/api/v1/task/64850eeb0dd4b973eaf656dc
